CLASS zcl_00_event_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  FOR EVENTS OF z00_r_travel .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_00_event_handler IMPLEMENTATION.
ENDCLASS.
